---
port: 8080
scan_interval: 60 # The interval in minutes between scans of the manga library.
database:
  # The path to the SQLite database file.
  path: "./mango.db"
library:
  # The root directory of your manga library.
  path: "./manga"
plugins:
  # The path to the plugins directory.
  path: "../mango-go-plugins"
  unload_timeout: 30 # The time in minutes after which idle plugins are unloaded.